// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

#ifndef PROTOBUF_sample_2eproto__INCLUDED
#define PROTOBUF_sample_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "types.pb.h"
// @@protoc_insertion_point(includes)

namespace packets {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_sample_2eproto();
void protobuf_AssignDesc_sample_2eproto();
void protobuf_ShutdownFile_sample_2eproto();

class CharSelectAck;
class CharSelectReq;
class EnterPacket;
class EnterWorld;
class LeavePacket;
class LeaveWorld;
class LoginAck;
class LoginReq;
class Move;
class PingReq;
class UpdateDispatchReq;
class UpdateDispatchReq_UpdateGold;
class UpdateDispatchReq_UpdateGold_GoldData;
class UpdateDispatchReq_UpdateItem;
class UpdateDispatchReq_UpdateItem_ItemData;
class VSDisconnectNotify;
class VSDisconnectReq;
class ZoneMoveAck;
class ZoneMoveReq;

// ===================================================================

class EnterWorld : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.EnterWorld) */ {
 public:
  EnterWorld();
  virtual ~EnterWorld();

  EnterWorld(const EnterWorld& from);

  inline EnterWorld& operator=(const EnterWorld& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnterWorld& default_instance();

  void Swap(EnterWorld* other);

  // implements Message ----------------------------------------------

  inline EnterWorld* New() const { return New(NULL); }

  EnterWorld* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EnterWorld& from);
  void MergeFrom(const EnterWorld& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EnterWorld* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 ActorID = 1;
  void clear_actorid();
  static const int kActorIDFieldNumber = 1;
  ::google::protobuf::int64 actorid() const;
  void set_actorid(::google::protobuf::int64 value);

  // optional int32 ZoneID = 2;
  void clear_zoneid();
  static const int kZoneIDFieldNumber = 2;
  ::google::protobuf::int32 zoneid() const;
  void set_zoneid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:packets.EnterWorld)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 actorid_;
  ::google::protobuf::int32 zoneid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static EnterWorld* default_instance_;
};
// -------------------------------------------------------------------

class EnterPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.EnterPacket) */ {
 public:
  EnterPacket();
  virtual ~EnterPacket();

  EnterPacket(const EnterPacket& from);

  inline EnterPacket& operator=(const EnterPacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnterPacket& default_instance();

  void Swap(EnterPacket* other);

  // implements Message ----------------------------------------------

  inline EnterPacket* New() const { return New(NULL); }

  EnterPacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EnterPacket& from);
  void MergeFrom(const EnterPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EnterPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packets.ActorType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::packets::ActorType type() const;
  void set_type(::packets::ActorType value);

  // optional int64 ActorID = 2;
  void clear_actorid();
  static const int kActorIDFieldNumber = 2;
  ::google::protobuf::int64 actorid() const;
  void set_actorid(::google::protobuf::int64 value);

  // optional .packets.Vector3 Position = 3;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 3;
  const ::packets::Vector3& position() const;
  ::packets::Vector3* mutable_position();
  ::packets::Vector3* release_position();
  void set_allocated_position(::packets::Vector3* position);

  // @@protoc_insertion_point(class_scope:packets.EnterPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 actorid_;
  ::packets::Vector3* position_;
  int type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static EnterPacket* default_instance_;
};
// -------------------------------------------------------------------

class Move : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.Move) */ {
 public:
  Move();
  virtual ~Move();

  Move(const Move& from);

  inline Move& operator=(const Move& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Move& default_instance();

  void Swap(Move* other);

  // implements Message ----------------------------------------------

  inline Move* New() const { return New(NULL); }

  Move* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Move& from);
  void MergeFrom(const Move& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Move* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 ActorID = 1;
  void clear_actorid();
  static const int kActorIDFieldNumber = 1;
  ::google::protobuf::int64 actorid() const;
  void set_actorid(::google::protobuf::int64 value);

  // optional .packets.Vector3 Position = 2;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 2;
  const ::packets::Vector3& position() const;
  ::packets::Vector3* mutable_position();
  ::packets::Vector3* release_position();
  void set_allocated_position(::packets::Vector3* position);

  // @@protoc_insertion_point(class_scope:packets.Move)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 actorid_;
  ::packets::Vector3* position_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static Move* default_instance_;
};
// -------------------------------------------------------------------

class LeaveWorld : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.LeaveWorld) */ {
 public:
  LeaveWorld();
  virtual ~LeaveWorld();

  LeaveWorld(const LeaveWorld& from);

  inline LeaveWorld& operator=(const LeaveWorld& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LeaveWorld& default_instance();

  void Swap(LeaveWorld* other);

  // implements Message ----------------------------------------------

  inline LeaveWorld* New() const { return New(NULL); }

  LeaveWorld* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LeaveWorld& from);
  void MergeFrom(const LeaveWorld& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LeaveWorld* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:packets.LeaveWorld)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static LeaveWorld* default_instance_;
};
// -------------------------------------------------------------------

class LeavePacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.LeavePacket) */ {
 public:
  LeavePacket();
  virtual ~LeavePacket();

  LeavePacket(const LeavePacket& from);

  inline LeavePacket& operator=(const LeavePacket& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LeavePacket& default_instance();

  void Swap(LeavePacket* other);

  // implements Message ----------------------------------------------

  inline LeavePacket* New() const { return New(NULL); }

  LeavePacket* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LeavePacket& from);
  void MergeFrom(const LeavePacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LeavePacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 ActorID = 1;
  void clear_actorid();
  static const int kActorIDFieldNumber = 1;
  ::google::protobuf::int64 actorid() const;
  void set_actorid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:packets.LeavePacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 actorid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static LeavePacket* default_instance_;
};
// -------------------------------------------------------------------

class LoginReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.LoginReq) */ {
 public:
  LoginReq();
  virtual ~LoginReq();

  LoginReq(const LoginReq& from);

  inline LoginReq& operator=(const LoginReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginReq& default_instance();

  void Swap(LoginReq* other);

  // implements Message ----------------------------------------------

  inline LoginReq* New() const { return New(NULL); }

  LoginReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginReq& from);
  void MergeFrom(const LoginReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional string Pass = 2;
  void clear_pass();
  static const int kPassFieldNumber = 2;
  const ::std::string& pass() const;
  void set_pass(const ::std::string& value);
  void set_pass(const char* value);
  void set_pass(const char* value, size_t size);
  ::std::string* mutable_pass();
  ::std::string* release_pass();
  void set_allocated_pass(::std::string* pass);

  // optional int64 SerialID = 3;
  void clear_serialid();
  static const int kSerialIDFieldNumber = 3;
  ::google::protobuf::int64 serialid() const;
  void set_serialid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:packets.LoginReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr pass_;
  ::google::protobuf::int64 serialid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static LoginReq* default_instance_;
};
// -------------------------------------------------------------------

class LoginAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.LoginAck) */ {
 public:
  LoginAck();
  virtual ~LoginAck();

  LoginAck(const LoginAck& from);

  inline LoginAck& operator=(const LoginAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginAck& default_instance();

  void Swap(LoginAck* other);

  // implements Message ----------------------------------------------

  inline LoginAck* New() const { return New(NULL); }

  LoginAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginAck& from);
  void MergeFrom(const LoginAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 UserID = 1;
  void clear_userid();
  static const int kUserIDFieldNumber = 1;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // optional int64 ActorID = 2;
  void clear_actorid();
  static const int kActorIDFieldNumber = 2;
  ::google::protobuf::int64 actorid() const;
  void set_actorid(::google::protobuf::int64 value);

  // optional .packets.ResultType Result = 3;
  void clear_result();
  static const int kResultFieldNumber = 3;
  ::packets::ResultType result() const;
  void set_result(::packets::ResultType value);

  // @@protoc_insertion_point(class_scope:packets.LoginAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 userid_;
  ::google::protobuf::int64 actorid_;
  int result_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static LoginAck* default_instance_;
};
// -------------------------------------------------------------------

class CharSelectReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.CharSelectReq) */ {
 public:
  CharSelectReq();
  virtual ~CharSelectReq();

  CharSelectReq(const CharSelectReq& from);

  inline CharSelectReq& operator=(const CharSelectReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CharSelectReq& default_instance();

  void Swap(CharSelectReq* other);

  // implements Message ----------------------------------------------

  inline CharSelectReq* New() const { return New(NULL); }

  CharSelectReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CharSelectReq& from);
  void MergeFrom(const CharSelectReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CharSelectReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 ClassType = 1;
  void clear_classtype();
  static const int kClassTypeFieldNumber = 1;
  ::google::protobuf::int64 classtype() const;
  void set_classtype(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:packets.CharSelectReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 classtype_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static CharSelectReq* default_instance_;
};
// -------------------------------------------------------------------

class CharSelectAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.CharSelectAck) */ {
 public:
  CharSelectAck();
  virtual ~CharSelectAck();

  CharSelectAck(const CharSelectAck& from);

  inline CharSelectAck& operator=(const CharSelectAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CharSelectAck& default_instance();

  void Swap(CharSelectAck* other);

  // implements Message ----------------------------------------------

  inline CharSelectAck* New() const { return New(NULL); }

  CharSelectAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CharSelectAck& from);
  void MergeFrom(const CharSelectAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CharSelectAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool IsNewChar = 1;
  void clear_isnewchar();
  static const int kIsNewCharFieldNumber = 1;
  bool isnewchar() const;
  void set_isnewchar(bool value);

  // optional int64 UserID = 2;
  void clear_userid();
  static const int kUserIDFieldNumber = 2;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // optional int64 ActorID = 3;
  void clear_actorid();
  static const int kActorIDFieldNumber = 3;
  ::google::protobuf::int64 actorid() const;
  void set_actorid(::google::protobuf::int64 value);

  // optional int32 ZoneID = 4;
  void clear_zoneid();
  static const int kZoneIDFieldNumber = 4;
  ::google::protobuf::int32 zoneid() const;
  void set_zoneid(::google::protobuf::int32 value);

  // optional .packets.ResultType Result = 5;
  void clear_result();
  static const int kResultFieldNumber = 5;
  ::packets::ResultType result() const;
  void set_result(::packets::ResultType value);

  // @@protoc_insertion_point(class_scope:packets.CharSelectAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 userid_;
  bool isnewchar_;
  ::google::protobuf::int32 zoneid_;
  ::google::protobuf::int64 actorid_;
  int result_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static CharSelectAck* default_instance_;
};
// -------------------------------------------------------------------

class ZoneMoveReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.ZoneMoveReq) */ {
 public:
  ZoneMoveReq();
  virtual ~ZoneMoveReq();

  ZoneMoveReq(const ZoneMoveReq& from);

  inline ZoneMoveReq& operator=(const ZoneMoveReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZoneMoveReq& default_instance();

  void Swap(ZoneMoveReq* other);

  // implements Message ----------------------------------------------

  inline ZoneMoveReq* New() const { return New(NULL); }

  ZoneMoveReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZoneMoveReq& from);
  void MergeFrom(const ZoneMoveReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ZoneMoveReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ZoneID = 1;
  void clear_zoneid();
  static const int kZoneIDFieldNumber = 1;
  ::google::protobuf::int32 zoneid() const;
  void set_zoneid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:packets.ZoneMoveReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 zoneid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static ZoneMoveReq* default_instance_;
};
// -------------------------------------------------------------------

class ZoneMoveAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.ZoneMoveAck) */ {
 public:
  ZoneMoveAck();
  virtual ~ZoneMoveAck();

  ZoneMoveAck(const ZoneMoveAck& from);

  inline ZoneMoveAck& operator=(const ZoneMoveAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZoneMoveAck& default_instance();

  void Swap(ZoneMoveAck* other);

  // implements Message ----------------------------------------------

  inline ZoneMoveAck* New() const { return New(NULL); }

  ZoneMoveAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZoneMoveAck& from);
  void MergeFrom(const ZoneMoveAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ZoneMoveAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .packets.ResultType Result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::packets::ResultType result() const;
  void set_result(::packets::ResultType value);

  // @@protoc_insertion_point(class_scope:packets.ZoneMoveAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int result_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static ZoneMoveAck* default_instance_;
};
// -------------------------------------------------------------------

class PingReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.PingReq) */ {
 public:
  PingReq();
  virtual ~PingReq();

  PingReq(const PingReq& from);

  inline PingReq& operator=(const PingReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PingReq& default_instance();

  void Swap(PingReq* other);

  // implements Message ----------------------------------------------

  inline PingReq* New() const { return New(NULL); }

  PingReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PingReq& from);
  void MergeFrom(const PingReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PingReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:packets.PingReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static PingReq* default_instance_;
};
// -------------------------------------------------------------------

class UpdateDispatchReq_UpdateGold_GoldData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.UpdateDispatchReq.UpdateGold.GoldData) */ {
 public:
  UpdateDispatchReq_UpdateGold_GoldData();
  virtual ~UpdateDispatchReq_UpdateGold_GoldData();

  UpdateDispatchReq_UpdateGold_GoldData(const UpdateDispatchReq_UpdateGold_GoldData& from);

  inline UpdateDispatchReq_UpdateGold_GoldData& operator=(const UpdateDispatchReq_UpdateGold_GoldData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateDispatchReq_UpdateGold_GoldData& default_instance();

  void Swap(UpdateDispatchReq_UpdateGold_GoldData* other);

  // implements Message ----------------------------------------------

  inline UpdateDispatchReq_UpdateGold_GoldData* New() const { return New(NULL); }

  UpdateDispatchReq_UpdateGold_GoldData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateDispatchReq_UpdateGold_GoldData& from);
  void MergeFrom(const UpdateDispatchReq_UpdateGold_GoldData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateDispatchReq_UpdateGold_GoldData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 MoneyType = 1;
  void clear_moneytype();
  static const int kMoneyTypeFieldNumber = 1;
  ::google::protobuf::int32 moneytype() const;
  void set_moneytype(::google::protobuf::int32 value);

  // optional int64 Add = 2;
  void clear_add();
  static const int kAddFieldNumber = 2;
  ::google::protobuf::int64 add() const;
  void set_add(::google::protobuf::int64 value);

  // optional int64 Total = 3;
  void clear_total();
  static const int kTotalFieldNumber = 3;
  ::google::protobuf::int64 total() const;
  void set_total(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:packets.UpdateDispatchReq.UpdateGold.GoldData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 add_;
  ::google::protobuf::int64 total_;
  ::google::protobuf::int32 moneytype_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static UpdateDispatchReq_UpdateGold_GoldData* default_instance_;
};
// -------------------------------------------------------------------

class UpdateDispatchReq_UpdateGold : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.UpdateDispatchReq.UpdateGold) */ {
 public:
  UpdateDispatchReq_UpdateGold();
  virtual ~UpdateDispatchReq_UpdateGold();

  UpdateDispatchReq_UpdateGold(const UpdateDispatchReq_UpdateGold& from);

  inline UpdateDispatchReq_UpdateGold& operator=(const UpdateDispatchReq_UpdateGold& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateDispatchReq_UpdateGold& default_instance();

  void Swap(UpdateDispatchReq_UpdateGold* other);

  // implements Message ----------------------------------------------

  inline UpdateDispatchReq_UpdateGold* New() const { return New(NULL); }

  UpdateDispatchReq_UpdateGold* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateDispatchReq_UpdateGold& from);
  void MergeFrom(const UpdateDispatchReq_UpdateGold& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateDispatchReq_UpdateGold* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef UpdateDispatchReq_UpdateGold_GoldData GoldData;

  // accessors -------------------------------------------------------

  // repeated .packets.UpdateDispatchReq.UpdateGold.GoldData GoldList = 1;
  int goldlist_size() const;
  void clear_goldlist();
  static const int kGoldListFieldNumber = 1;
  const ::packets::UpdateDispatchReq_UpdateGold_GoldData& goldlist(int index) const;
  ::packets::UpdateDispatchReq_UpdateGold_GoldData* mutable_goldlist(int index);
  ::packets::UpdateDispatchReq_UpdateGold_GoldData* add_goldlist();
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold_GoldData >*
      mutable_goldlist();
  const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold_GoldData >&
      goldlist() const;

  // @@protoc_insertion_point(class_scope:packets.UpdateDispatchReq.UpdateGold)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold_GoldData > goldlist_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static UpdateDispatchReq_UpdateGold* default_instance_;
};
// -------------------------------------------------------------------

class UpdateDispatchReq_UpdateItem_ItemData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.UpdateDispatchReq.UpdateItem.ItemData) */ {
 public:
  UpdateDispatchReq_UpdateItem_ItemData();
  virtual ~UpdateDispatchReq_UpdateItem_ItemData();

  UpdateDispatchReq_UpdateItem_ItemData(const UpdateDispatchReq_UpdateItem_ItemData& from);

  inline UpdateDispatchReq_UpdateItem_ItemData& operator=(const UpdateDispatchReq_UpdateItem_ItemData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateDispatchReq_UpdateItem_ItemData& default_instance();

  void Swap(UpdateDispatchReq_UpdateItem_ItemData* other);

  // implements Message ----------------------------------------------

  inline UpdateDispatchReq_UpdateItem_ItemData* New() const { return New(NULL); }

  UpdateDispatchReq_UpdateItem_ItemData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateDispatchReq_UpdateItem_ItemData& from);
  void MergeFrom(const UpdateDispatchReq_UpdateItem_ItemData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateDispatchReq_UpdateItem_ItemData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 SerialId = 1;
  void clear_serialid();
  static const int kSerialIdFieldNumber = 1;
  ::google::protobuf::int64 serialid() const;
  void set_serialid(::google::protobuf::int64 value);

  // optional int32 Durability = 2;
  void clear_durability();
  static const int kDurabilityFieldNumber = 2;
  ::google::protobuf::int32 durability() const;
  void set_durability(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:packets.UpdateDispatchReq.UpdateItem.ItemData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 serialid_;
  ::google::protobuf::int32 durability_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static UpdateDispatchReq_UpdateItem_ItemData* default_instance_;
};
// -------------------------------------------------------------------

class UpdateDispatchReq_UpdateItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.UpdateDispatchReq.UpdateItem) */ {
 public:
  UpdateDispatchReq_UpdateItem();
  virtual ~UpdateDispatchReq_UpdateItem();

  UpdateDispatchReq_UpdateItem(const UpdateDispatchReq_UpdateItem& from);

  inline UpdateDispatchReq_UpdateItem& operator=(const UpdateDispatchReq_UpdateItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateDispatchReq_UpdateItem& default_instance();

  void Swap(UpdateDispatchReq_UpdateItem* other);

  // implements Message ----------------------------------------------

  inline UpdateDispatchReq_UpdateItem* New() const { return New(NULL); }

  UpdateDispatchReq_UpdateItem* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateDispatchReq_UpdateItem& from);
  void MergeFrom(const UpdateDispatchReq_UpdateItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateDispatchReq_UpdateItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef UpdateDispatchReq_UpdateItem_ItemData ItemData;

  // accessors -------------------------------------------------------

  // repeated .packets.UpdateDispatchReq.UpdateItem.ItemData AddList = 1;
  int addlist_size() const;
  void clear_addlist();
  static const int kAddListFieldNumber = 1;
  const ::packets::UpdateDispatchReq_UpdateItem_ItemData& addlist(int index) const;
  ::packets::UpdateDispatchReq_UpdateItem_ItemData* mutable_addlist(int index);
  ::packets::UpdateDispatchReq_UpdateItem_ItemData* add_addlist();
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >*
      mutable_addlist();
  const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >&
      addlist() const;

  // repeated .packets.UpdateDispatchReq.UpdateItem.ItemData DeleteList = 2;
  int deletelist_size() const;
  void clear_deletelist();
  static const int kDeleteListFieldNumber = 2;
  const ::packets::UpdateDispatchReq_UpdateItem_ItemData& deletelist(int index) const;
  ::packets::UpdateDispatchReq_UpdateItem_ItemData* mutable_deletelist(int index);
  ::packets::UpdateDispatchReq_UpdateItem_ItemData* add_deletelist();
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >*
      mutable_deletelist();
  const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >&
      deletelist() const;

  // repeated .packets.UpdateDispatchReq.UpdateItem.ItemData UpdateList = 3;
  int updatelist_size() const;
  void clear_updatelist();
  static const int kUpdateListFieldNumber = 3;
  const ::packets::UpdateDispatchReq_UpdateItem_ItemData& updatelist(int index) const;
  ::packets::UpdateDispatchReq_UpdateItem_ItemData* mutable_updatelist(int index);
  ::packets::UpdateDispatchReq_UpdateItem_ItemData* add_updatelist();
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >*
      mutable_updatelist();
  const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >&
      updatelist() const;

  // @@protoc_insertion_point(class_scope:packets.UpdateDispatchReq.UpdateItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData > addlist_;
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData > deletelist_;
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData > updatelist_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static UpdateDispatchReq_UpdateItem* default_instance_;
};
// -------------------------------------------------------------------

class UpdateDispatchReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.UpdateDispatchReq) */ {
 public:
  UpdateDispatchReq();
  virtual ~UpdateDispatchReq();

  UpdateDispatchReq(const UpdateDispatchReq& from);

  inline UpdateDispatchReq& operator=(const UpdateDispatchReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateDispatchReq& default_instance();

  void Swap(UpdateDispatchReq* other);

  // implements Message ----------------------------------------------

  inline UpdateDispatchReq* New() const { return New(NULL); }

  UpdateDispatchReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateDispatchReq& from);
  void MergeFrom(const UpdateDispatchReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UpdateDispatchReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef UpdateDispatchReq_UpdateGold UpdateGold;
  typedef UpdateDispatchReq_UpdateItem UpdateItem;

  // accessors -------------------------------------------------------

  // optional int64 UserID = 1;
  void clear_userid();
  static const int kUserIDFieldNumber = 1;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // repeated .packets.UpdateDispatchReq.UpdateGold GoldList = 2;
  int goldlist_size() const;
  void clear_goldlist();
  static const int kGoldListFieldNumber = 2;
  const ::packets::UpdateDispatchReq_UpdateGold& goldlist(int index) const;
  ::packets::UpdateDispatchReq_UpdateGold* mutable_goldlist(int index);
  ::packets::UpdateDispatchReq_UpdateGold* add_goldlist();
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold >*
      mutable_goldlist();
  const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold >&
      goldlist() const;

  // repeated .packets.UpdateDispatchReq.UpdateItem ItemList = 3;
  int itemlist_size() const;
  void clear_itemlist();
  static const int kItemListFieldNumber = 3;
  const ::packets::UpdateDispatchReq_UpdateItem& itemlist(int index) const;
  ::packets::UpdateDispatchReq_UpdateItem* mutable_itemlist(int index);
  ::packets::UpdateDispatchReq_UpdateItem* add_itemlist();
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem >*
      mutable_itemlist();
  const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem >&
      itemlist() const;

  // @@protoc_insertion_point(class_scope:packets.UpdateDispatchReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 userid_;
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold > goldlist_;
  ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem > itemlist_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static UpdateDispatchReq* default_instance_;
};
// -------------------------------------------------------------------

class VSDisconnectReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.VSDisconnectReq) */ {
 public:
  VSDisconnectReq();
  virtual ~VSDisconnectReq();

  VSDisconnectReq(const VSDisconnectReq& from);

  inline VSDisconnectReq& operator=(const VSDisconnectReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VSDisconnectReq& default_instance();

  void Swap(VSDisconnectReq* other);

  // implements Message ----------------------------------------------

  inline VSDisconnectReq* New() const { return New(NULL); }

  VSDisconnectReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VSDisconnectReq& from);
  void MergeFrom(const VSDisconnectReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VSDisconnectReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:packets.VSDisconnectReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static VSDisconnectReq* default_instance_;
};
// -------------------------------------------------------------------

class VSDisconnectNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:packets.VSDisconnectNotify) */ {
 public:
  VSDisconnectNotify();
  virtual ~VSDisconnectNotify();

  VSDisconnectNotify(const VSDisconnectNotify& from);

  inline VSDisconnectNotify& operator=(const VSDisconnectNotify& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VSDisconnectNotify& default_instance();

  void Swap(VSDisconnectNotify* other);

  // implements Message ----------------------------------------------

  inline VSDisconnectNotify* New() const { return New(NULL); }

  VSDisconnectNotify* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VSDisconnectNotify& from);
  void MergeFrom(const VSDisconnectNotify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VSDisconnectNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:packets.VSDisconnectNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_sample_2eproto();
  friend void protobuf_AssignDesc_sample_2eproto();
  friend void protobuf_ShutdownFile_sample_2eproto();

  void InitAsDefaultInstance();
  static VSDisconnectNotify* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// EnterWorld

// optional int64 ActorID = 1;
inline void EnterWorld::clear_actorid() {
  actorid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 EnterWorld::actorid() const {
  // @@protoc_insertion_point(field_get:packets.EnterWorld.ActorID)
  return actorid_;
}
inline void EnterWorld::set_actorid(::google::protobuf::int64 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:packets.EnterWorld.ActorID)
}

// optional int32 ZoneID = 2;
inline void EnterWorld::clear_zoneid() {
  zoneid_ = 0;
}
inline ::google::protobuf::int32 EnterWorld::zoneid() const {
  // @@protoc_insertion_point(field_get:packets.EnterWorld.ZoneID)
  return zoneid_;
}
inline void EnterWorld::set_zoneid(::google::protobuf::int32 value) {
  
  zoneid_ = value;
  // @@protoc_insertion_point(field_set:packets.EnterWorld.ZoneID)
}

// -------------------------------------------------------------------

// EnterPacket

// optional .packets.ActorType type = 1;
inline void EnterPacket::clear_type() {
  type_ = 0;
}
inline ::packets::ActorType EnterPacket::type() const {
  // @@protoc_insertion_point(field_get:packets.EnterPacket.type)
  return static_cast< ::packets::ActorType >(type_);
}
inline void EnterPacket::set_type(::packets::ActorType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:packets.EnterPacket.type)
}

// optional int64 ActorID = 2;
inline void EnterPacket::clear_actorid() {
  actorid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 EnterPacket::actorid() const {
  // @@protoc_insertion_point(field_get:packets.EnterPacket.ActorID)
  return actorid_;
}
inline void EnterPacket::set_actorid(::google::protobuf::int64 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:packets.EnterPacket.ActorID)
}

// optional .packets.Vector3 Position = 3;
inline bool EnterPacket::has_position() const {
  return !_is_default_instance_ && position_ != NULL;
}
inline void EnterPacket::clear_position() {
  if (GetArenaNoVirtual() == NULL && position_ != NULL) delete position_;
  position_ = NULL;
}
inline const ::packets::Vector3& EnterPacket::position() const {
  // @@protoc_insertion_point(field_get:packets.EnterPacket.Position)
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
inline ::packets::Vector3* EnterPacket::mutable_position() {
  
  if (position_ == NULL) {
    position_ = new ::packets::Vector3;
  }
  // @@protoc_insertion_point(field_mutable:packets.EnterPacket.Position)
  return position_;
}
inline ::packets::Vector3* EnterPacket::release_position() {
  // @@protoc_insertion_point(field_release:packets.EnterPacket.Position)
  
  ::packets::Vector3* temp = position_;
  position_ = NULL;
  return temp;
}
inline void EnterPacket::set_allocated_position(::packets::Vector3* position) {
  delete position_;
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:packets.EnterPacket.Position)
}

// -------------------------------------------------------------------

// Move

// optional int64 ActorID = 1;
inline void Move::clear_actorid() {
  actorid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Move::actorid() const {
  // @@protoc_insertion_point(field_get:packets.Move.ActorID)
  return actorid_;
}
inline void Move::set_actorid(::google::protobuf::int64 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:packets.Move.ActorID)
}

// optional .packets.Vector3 Position = 2;
inline bool Move::has_position() const {
  return !_is_default_instance_ && position_ != NULL;
}
inline void Move::clear_position() {
  if (GetArenaNoVirtual() == NULL && position_ != NULL) delete position_;
  position_ = NULL;
}
inline const ::packets::Vector3& Move::position() const {
  // @@protoc_insertion_point(field_get:packets.Move.Position)
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
inline ::packets::Vector3* Move::mutable_position() {
  
  if (position_ == NULL) {
    position_ = new ::packets::Vector3;
  }
  // @@protoc_insertion_point(field_mutable:packets.Move.Position)
  return position_;
}
inline ::packets::Vector3* Move::release_position() {
  // @@protoc_insertion_point(field_release:packets.Move.Position)
  
  ::packets::Vector3* temp = position_;
  position_ = NULL;
  return temp;
}
inline void Move::set_allocated_position(::packets::Vector3* position) {
  delete position_;
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:packets.Move.Position)
}

// -------------------------------------------------------------------

// LeaveWorld

// -------------------------------------------------------------------

// LeavePacket

// optional int64 ActorID = 1;
inline void LeavePacket::clear_actorid() {
  actorid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LeavePacket::actorid() const {
  // @@protoc_insertion_point(field_get:packets.LeavePacket.ActorID)
  return actorid_;
}
inline void LeavePacket::set_actorid(::google::protobuf::int64 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:packets.LeavePacket.ActorID)
}

// -------------------------------------------------------------------

// LoginReq

// optional string ID = 1;
inline void LoginReq::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginReq::id() const {
  // @@protoc_insertion_point(field_get:packets.LoginReq.ID)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packets.LoginReq.ID)
}
inline void LoginReq::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packets.LoginReq.ID)
}
inline void LoginReq::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packets.LoginReq.ID)
}
inline ::std::string* LoginReq::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:packets.LoginReq.ID)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginReq::release_id() {
  // @@protoc_insertion_point(field_release:packets.LoginReq.ID)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:packets.LoginReq.ID)
}

// optional string Pass = 2;
inline void LoginReq::clear_pass() {
  pass_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoginReq::pass() const {
  // @@protoc_insertion_point(field_get:packets.LoginReq.Pass)
  return pass_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_pass(const ::std::string& value) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packets.LoginReq.Pass)
}
inline void LoginReq::set_pass(const char* value) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packets.LoginReq.Pass)
}
inline void LoginReq::set_pass(const char* value, size_t size) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packets.LoginReq.Pass)
}
inline ::std::string* LoginReq::mutable_pass() {
  
  // @@protoc_insertion_point(field_mutable:packets.LoginReq.Pass)
  return pass_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginReq::release_pass() {
  // @@protoc_insertion_point(field_release:packets.LoginReq.Pass)
  
  return pass_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginReq::set_allocated_pass(::std::string* pass) {
  if (pass != NULL) {
    
  } else {
    
  }
  pass_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pass);
  // @@protoc_insertion_point(field_set_allocated:packets.LoginReq.Pass)
}

// optional int64 SerialID = 3;
inline void LoginReq::clear_serialid() {
  serialid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LoginReq::serialid() const {
  // @@protoc_insertion_point(field_get:packets.LoginReq.SerialID)
  return serialid_;
}
inline void LoginReq::set_serialid(::google::protobuf::int64 value) {
  
  serialid_ = value;
  // @@protoc_insertion_point(field_set:packets.LoginReq.SerialID)
}

// -------------------------------------------------------------------

// LoginAck

// optional int64 UserID = 1;
inline void LoginAck::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LoginAck::userid() const {
  // @@protoc_insertion_point(field_get:packets.LoginAck.UserID)
  return userid_;
}
inline void LoginAck::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:packets.LoginAck.UserID)
}

// optional int64 ActorID = 2;
inline void LoginAck::clear_actorid() {
  actorid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LoginAck::actorid() const {
  // @@protoc_insertion_point(field_get:packets.LoginAck.ActorID)
  return actorid_;
}
inline void LoginAck::set_actorid(::google::protobuf::int64 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:packets.LoginAck.ActorID)
}

// optional .packets.ResultType Result = 3;
inline void LoginAck::clear_result() {
  result_ = 0;
}
inline ::packets::ResultType LoginAck::result() const {
  // @@protoc_insertion_point(field_get:packets.LoginAck.Result)
  return static_cast< ::packets::ResultType >(result_);
}
inline void LoginAck::set_result(::packets::ResultType value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:packets.LoginAck.Result)
}

// -------------------------------------------------------------------

// CharSelectReq

// optional int64 ClassType = 1;
inline void CharSelectReq::clear_classtype() {
  classtype_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 CharSelectReq::classtype() const {
  // @@protoc_insertion_point(field_get:packets.CharSelectReq.ClassType)
  return classtype_;
}
inline void CharSelectReq::set_classtype(::google::protobuf::int64 value) {
  
  classtype_ = value;
  // @@protoc_insertion_point(field_set:packets.CharSelectReq.ClassType)
}

// -------------------------------------------------------------------

// CharSelectAck

// optional bool IsNewChar = 1;
inline void CharSelectAck::clear_isnewchar() {
  isnewchar_ = false;
}
inline bool CharSelectAck::isnewchar() const {
  // @@protoc_insertion_point(field_get:packets.CharSelectAck.IsNewChar)
  return isnewchar_;
}
inline void CharSelectAck::set_isnewchar(bool value) {
  
  isnewchar_ = value;
  // @@protoc_insertion_point(field_set:packets.CharSelectAck.IsNewChar)
}

// optional int64 UserID = 2;
inline void CharSelectAck::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 CharSelectAck::userid() const {
  // @@protoc_insertion_point(field_get:packets.CharSelectAck.UserID)
  return userid_;
}
inline void CharSelectAck::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:packets.CharSelectAck.UserID)
}

// optional int64 ActorID = 3;
inline void CharSelectAck::clear_actorid() {
  actorid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 CharSelectAck::actorid() const {
  // @@protoc_insertion_point(field_get:packets.CharSelectAck.ActorID)
  return actorid_;
}
inline void CharSelectAck::set_actorid(::google::protobuf::int64 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:packets.CharSelectAck.ActorID)
}

// optional int32 ZoneID = 4;
inline void CharSelectAck::clear_zoneid() {
  zoneid_ = 0;
}
inline ::google::protobuf::int32 CharSelectAck::zoneid() const {
  // @@protoc_insertion_point(field_get:packets.CharSelectAck.ZoneID)
  return zoneid_;
}
inline void CharSelectAck::set_zoneid(::google::protobuf::int32 value) {
  
  zoneid_ = value;
  // @@protoc_insertion_point(field_set:packets.CharSelectAck.ZoneID)
}

// optional .packets.ResultType Result = 5;
inline void CharSelectAck::clear_result() {
  result_ = 0;
}
inline ::packets::ResultType CharSelectAck::result() const {
  // @@protoc_insertion_point(field_get:packets.CharSelectAck.Result)
  return static_cast< ::packets::ResultType >(result_);
}
inline void CharSelectAck::set_result(::packets::ResultType value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:packets.CharSelectAck.Result)
}

// -------------------------------------------------------------------

// ZoneMoveReq

// optional int32 ZoneID = 1;
inline void ZoneMoveReq::clear_zoneid() {
  zoneid_ = 0;
}
inline ::google::protobuf::int32 ZoneMoveReq::zoneid() const {
  // @@protoc_insertion_point(field_get:packets.ZoneMoveReq.ZoneID)
  return zoneid_;
}
inline void ZoneMoveReq::set_zoneid(::google::protobuf::int32 value) {
  
  zoneid_ = value;
  // @@protoc_insertion_point(field_set:packets.ZoneMoveReq.ZoneID)
}

// -------------------------------------------------------------------

// ZoneMoveAck

// optional .packets.ResultType Result = 1;
inline void ZoneMoveAck::clear_result() {
  result_ = 0;
}
inline ::packets::ResultType ZoneMoveAck::result() const {
  // @@protoc_insertion_point(field_get:packets.ZoneMoveAck.Result)
  return static_cast< ::packets::ResultType >(result_);
}
inline void ZoneMoveAck::set_result(::packets::ResultType value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:packets.ZoneMoveAck.Result)
}

// -------------------------------------------------------------------

// PingReq

// -------------------------------------------------------------------

// UpdateDispatchReq_UpdateGold_GoldData

// optional int32 MoneyType = 1;
inline void UpdateDispatchReq_UpdateGold_GoldData::clear_moneytype() {
  moneytype_ = 0;
}
inline ::google::protobuf::int32 UpdateDispatchReq_UpdateGold_GoldData::moneytype() const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateGold.GoldData.MoneyType)
  return moneytype_;
}
inline void UpdateDispatchReq_UpdateGold_GoldData::set_moneytype(::google::protobuf::int32 value) {
  
  moneytype_ = value;
  // @@protoc_insertion_point(field_set:packets.UpdateDispatchReq.UpdateGold.GoldData.MoneyType)
}

// optional int64 Add = 2;
inline void UpdateDispatchReq_UpdateGold_GoldData::clear_add() {
  add_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UpdateDispatchReq_UpdateGold_GoldData::add() const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateGold.GoldData.Add)
  return add_;
}
inline void UpdateDispatchReq_UpdateGold_GoldData::set_add(::google::protobuf::int64 value) {
  
  add_ = value;
  // @@protoc_insertion_point(field_set:packets.UpdateDispatchReq.UpdateGold.GoldData.Add)
}

// optional int64 Total = 3;
inline void UpdateDispatchReq_UpdateGold_GoldData::clear_total() {
  total_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UpdateDispatchReq_UpdateGold_GoldData::total() const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateGold.GoldData.Total)
  return total_;
}
inline void UpdateDispatchReq_UpdateGold_GoldData::set_total(::google::protobuf::int64 value) {
  
  total_ = value;
  // @@protoc_insertion_point(field_set:packets.UpdateDispatchReq.UpdateGold.GoldData.Total)
}

// -------------------------------------------------------------------

// UpdateDispatchReq_UpdateGold

// repeated .packets.UpdateDispatchReq.UpdateGold.GoldData GoldList = 1;
inline int UpdateDispatchReq_UpdateGold::goldlist_size() const {
  return goldlist_.size();
}
inline void UpdateDispatchReq_UpdateGold::clear_goldlist() {
  goldlist_.Clear();
}
inline const ::packets::UpdateDispatchReq_UpdateGold_GoldData& UpdateDispatchReq_UpdateGold::goldlist(int index) const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateGold.GoldList)
  return goldlist_.Get(index);
}
inline ::packets::UpdateDispatchReq_UpdateGold_GoldData* UpdateDispatchReq_UpdateGold::mutable_goldlist(int index) {
  // @@protoc_insertion_point(field_mutable:packets.UpdateDispatchReq.UpdateGold.GoldList)
  return goldlist_.Mutable(index);
}
inline ::packets::UpdateDispatchReq_UpdateGold_GoldData* UpdateDispatchReq_UpdateGold::add_goldlist() {
  // @@protoc_insertion_point(field_add:packets.UpdateDispatchReq.UpdateGold.GoldList)
  return goldlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold_GoldData >*
UpdateDispatchReq_UpdateGold::mutable_goldlist() {
  // @@protoc_insertion_point(field_mutable_list:packets.UpdateDispatchReq.UpdateGold.GoldList)
  return &goldlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold_GoldData >&
UpdateDispatchReq_UpdateGold::goldlist() const {
  // @@protoc_insertion_point(field_list:packets.UpdateDispatchReq.UpdateGold.GoldList)
  return goldlist_;
}

// -------------------------------------------------------------------

// UpdateDispatchReq_UpdateItem_ItemData

// optional int64 SerialId = 1;
inline void UpdateDispatchReq_UpdateItem_ItemData::clear_serialid() {
  serialid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UpdateDispatchReq_UpdateItem_ItemData::serialid() const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateItem.ItemData.SerialId)
  return serialid_;
}
inline void UpdateDispatchReq_UpdateItem_ItemData::set_serialid(::google::protobuf::int64 value) {
  
  serialid_ = value;
  // @@protoc_insertion_point(field_set:packets.UpdateDispatchReq.UpdateItem.ItemData.SerialId)
}

// optional int32 Durability = 2;
inline void UpdateDispatchReq_UpdateItem_ItemData::clear_durability() {
  durability_ = 0;
}
inline ::google::protobuf::int32 UpdateDispatchReq_UpdateItem_ItemData::durability() const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateItem.ItemData.Durability)
  return durability_;
}
inline void UpdateDispatchReq_UpdateItem_ItemData::set_durability(::google::protobuf::int32 value) {
  
  durability_ = value;
  // @@protoc_insertion_point(field_set:packets.UpdateDispatchReq.UpdateItem.ItemData.Durability)
}

// -------------------------------------------------------------------

// UpdateDispatchReq_UpdateItem

// repeated .packets.UpdateDispatchReq.UpdateItem.ItemData AddList = 1;
inline int UpdateDispatchReq_UpdateItem::addlist_size() const {
  return addlist_.size();
}
inline void UpdateDispatchReq_UpdateItem::clear_addlist() {
  addlist_.Clear();
}
inline const ::packets::UpdateDispatchReq_UpdateItem_ItemData& UpdateDispatchReq_UpdateItem::addlist(int index) const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateItem.AddList)
  return addlist_.Get(index);
}
inline ::packets::UpdateDispatchReq_UpdateItem_ItemData* UpdateDispatchReq_UpdateItem::mutable_addlist(int index) {
  // @@protoc_insertion_point(field_mutable:packets.UpdateDispatchReq.UpdateItem.AddList)
  return addlist_.Mutable(index);
}
inline ::packets::UpdateDispatchReq_UpdateItem_ItemData* UpdateDispatchReq_UpdateItem::add_addlist() {
  // @@protoc_insertion_point(field_add:packets.UpdateDispatchReq.UpdateItem.AddList)
  return addlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >*
UpdateDispatchReq_UpdateItem::mutable_addlist() {
  // @@protoc_insertion_point(field_mutable_list:packets.UpdateDispatchReq.UpdateItem.AddList)
  return &addlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >&
UpdateDispatchReq_UpdateItem::addlist() const {
  // @@protoc_insertion_point(field_list:packets.UpdateDispatchReq.UpdateItem.AddList)
  return addlist_;
}

// repeated .packets.UpdateDispatchReq.UpdateItem.ItemData DeleteList = 2;
inline int UpdateDispatchReq_UpdateItem::deletelist_size() const {
  return deletelist_.size();
}
inline void UpdateDispatchReq_UpdateItem::clear_deletelist() {
  deletelist_.Clear();
}
inline const ::packets::UpdateDispatchReq_UpdateItem_ItemData& UpdateDispatchReq_UpdateItem::deletelist(int index) const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateItem.DeleteList)
  return deletelist_.Get(index);
}
inline ::packets::UpdateDispatchReq_UpdateItem_ItemData* UpdateDispatchReq_UpdateItem::mutable_deletelist(int index) {
  // @@protoc_insertion_point(field_mutable:packets.UpdateDispatchReq.UpdateItem.DeleteList)
  return deletelist_.Mutable(index);
}
inline ::packets::UpdateDispatchReq_UpdateItem_ItemData* UpdateDispatchReq_UpdateItem::add_deletelist() {
  // @@protoc_insertion_point(field_add:packets.UpdateDispatchReq.UpdateItem.DeleteList)
  return deletelist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >*
UpdateDispatchReq_UpdateItem::mutable_deletelist() {
  // @@protoc_insertion_point(field_mutable_list:packets.UpdateDispatchReq.UpdateItem.DeleteList)
  return &deletelist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >&
UpdateDispatchReq_UpdateItem::deletelist() const {
  // @@protoc_insertion_point(field_list:packets.UpdateDispatchReq.UpdateItem.DeleteList)
  return deletelist_;
}

// repeated .packets.UpdateDispatchReq.UpdateItem.ItemData UpdateList = 3;
inline int UpdateDispatchReq_UpdateItem::updatelist_size() const {
  return updatelist_.size();
}
inline void UpdateDispatchReq_UpdateItem::clear_updatelist() {
  updatelist_.Clear();
}
inline const ::packets::UpdateDispatchReq_UpdateItem_ItemData& UpdateDispatchReq_UpdateItem::updatelist(int index) const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UpdateItem.UpdateList)
  return updatelist_.Get(index);
}
inline ::packets::UpdateDispatchReq_UpdateItem_ItemData* UpdateDispatchReq_UpdateItem::mutable_updatelist(int index) {
  // @@protoc_insertion_point(field_mutable:packets.UpdateDispatchReq.UpdateItem.UpdateList)
  return updatelist_.Mutable(index);
}
inline ::packets::UpdateDispatchReq_UpdateItem_ItemData* UpdateDispatchReq_UpdateItem::add_updatelist() {
  // @@protoc_insertion_point(field_add:packets.UpdateDispatchReq.UpdateItem.UpdateList)
  return updatelist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >*
UpdateDispatchReq_UpdateItem::mutable_updatelist() {
  // @@protoc_insertion_point(field_mutable_list:packets.UpdateDispatchReq.UpdateItem.UpdateList)
  return &updatelist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem_ItemData >&
UpdateDispatchReq_UpdateItem::updatelist() const {
  // @@protoc_insertion_point(field_list:packets.UpdateDispatchReq.UpdateItem.UpdateList)
  return updatelist_;
}

// -------------------------------------------------------------------

// UpdateDispatchReq

// optional int64 UserID = 1;
inline void UpdateDispatchReq::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UpdateDispatchReq::userid() const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.UserID)
  return userid_;
}
inline void UpdateDispatchReq::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:packets.UpdateDispatchReq.UserID)
}

// repeated .packets.UpdateDispatchReq.UpdateGold GoldList = 2;
inline int UpdateDispatchReq::goldlist_size() const {
  return goldlist_.size();
}
inline void UpdateDispatchReq::clear_goldlist() {
  goldlist_.Clear();
}
inline const ::packets::UpdateDispatchReq_UpdateGold& UpdateDispatchReq::goldlist(int index) const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.GoldList)
  return goldlist_.Get(index);
}
inline ::packets::UpdateDispatchReq_UpdateGold* UpdateDispatchReq::mutable_goldlist(int index) {
  // @@protoc_insertion_point(field_mutable:packets.UpdateDispatchReq.GoldList)
  return goldlist_.Mutable(index);
}
inline ::packets::UpdateDispatchReq_UpdateGold* UpdateDispatchReq::add_goldlist() {
  // @@protoc_insertion_point(field_add:packets.UpdateDispatchReq.GoldList)
  return goldlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold >*
UpdateDispatchReq::mutable_goldlist() {
  // @@protoc_insertion_point(field_mutable_list:packets.UpdateDispatchReq.GoldList)
  return &goldlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateGold >&
UpdateDispatchReq::goldlist() const {
  // @@protoc_insertion_point(field_list:packets.UpdateDispatchReq.GoldList)
  return goldlist_;
}

// repeated .packets.UpdateDispatchReq.UpdateItem ItemList = 3;
inline int UpdateDispatchReq::itemlist_size() const {
  return itemlist_.size();
}
inline void UpdateDispatchReq::clear_itemlist() {
  itemlist_.Clear();
}
inline const ::packets::UpdateDispatchReq_UpdateItem& UpdateDispatchReq::itemlist(int index) const {
  // @@protoc_insertion_point(field_get:packets.UpdateDispatchReq.ItemList)
  return itemlist_.Get(index);
}
inline ::packets::UpdateDispatchReq_UpdateItem* UpdateDispatchReq::mutable_itemlist(int index) {
  // @@protoc_insertion_point(field_mutable:packets.UpdateDispatchReq.ItemList)
  return itemlist_.Mutable(index);
}
inline ::packets::UpdateDispatchReq_UpdateItem* UpdateDispatchReq::add_itemlist() {
  // @@protoc_insertion_point(field_add:packets.UpdateDispatchReq.ItemList)
  return itemlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem >*
UpdateDispatchReq::mutable_itemlist() {
  // @@protoc_insertion_point(field_mutable_list:packets.UpdateDispatchReq.ItemList)
  return &itemlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::packets::UpdateDispatchReq_UpdateItem >&
UpdateDispatchReq::itemlist() const {
  // @@protoc_insertion_point(field_list:packets.UpdateDispatchReq.ItemList)
  return itemlist_;
}

// -------------------------------------------------------------------

// VSDisconnectReq

// -------------------------------------------------------------------

// VSDisconnectNotify

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace packets

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sample_2eproto__INCLUDED
