
namespace ChatServerLib
{

	enum class ERROR_CODE : short
	{
		NONE = 0,

		UNASSIGNED_ERROR = 201,

		MAIN_INIT_NETWORK_INIT_FAIL = 206,

		USER_MGR_ID_DUPLICATION = 211,
		USER_MGR_MAX_USER_COUNT = 212,
		USER_MGR_INVALID_SESSION_INDEX = 213,
		USER_MGR_NOT_CONFIRM_USER = 214,
		USER_MGR_REMOVE_INVALID_SESSION = 221,

		ROOM_ENTER_INVALID_DOMAIN = 271,
		ROOM_ENTER_INVALID_LOBBY_INDEX = 272,
		ROOM_ENTER_INVALID_ROOM_INDEX = 273,
		ROOM_ENTER_CREATE_FAIL = 274,
		ROOM_ENTER_NOT_CREATED = 275,
		ROOM_ENTER_MEMBER_FULL = 276,
		ROOM_ENTER_EMPTY_ROOM = 277,

		MATCHING_FAIL = 278,

		ROOM_LEAVE_INVALID_DOMAIN = 286,
		ROOM_LEAVE_INVALID_LOBBY_INDEX = 287,
		ROOM_LEAVE_INVALID_ROOM_INDEX = 288,
		ROOM_LEAVE_NOT_CREATED = 289,
		ROOM_LEAVE_NOT_MEMBER = 290,

		ROOM_CHAT_INVALID_DOMAIN = 296,
		ROOM_CHAT_INVALID_LOBBY_INDEX = 297,
		ROOM_CHAT_INVALID_ROOM_INDEX = 298,

		GAME_NOT_YOUR_TURN = 300,
		GAME_PUT_ALREADY_EXIST = 301,
		GAME_PUT_SAM_SAM = 302,
		GAME_RESULT_BLACK_WIN = 303,
		GAME_RESULT_WHITE_WIN = 304,

		NOT_READY_EXIST = 305,
		NOT_YOUR_TURN = 306
	};
}
#pragma once
